website/azuread.erb
website/docs/index.html.markdown

~Intentionally not adding highlights to these since they span 3 different sections of the site~ on reflection added highlights

adding the `azure providers` to the sidebar

---

website/docs/auth/azure_cli.html.markdown
website/docs/auth/service_principal_client_certificate.html.markdown
website/docs/auth/service_principal_client_secret.html.markdown
website/docs/auth/service_principal_configuration.html.markdown

Guide for configuring a principal to manage AAD

---

website/docs/auth/service_principal_configuration.html.markdown

appId is not the expected it but objectId coming from service principal object

Putting right ID for the service principal.

---

website/docs/index.html.markdown

update doc for 0.3.0 relaese

---

website/azuread.erb
website/docs/r/service_principal.html.markdown

Add Service Principal Configuration guide to sidebar & azuread_service_principal docs

---

azuread/data_application.go
azuread/resource_application.go
azuread/resource_service_principal.go
azuread/resource_user.go

Should fix #4 (or at least help)

Application & Service Principal Creation should now wait on replication

---

azuread/resource_application.go
azuread/resource_application_test.go

this should address #88 the alternative was to either add some very complicated regex or an if on the validation dependant on type
I have left a comment in the test if anyone could help me understand what is going on there and make that better that would be great

removed reply_urls validation

---

website/docs/r/user.html.markdown

This is just a PR to document working functionality, which was missing in the docs.

azuread user - import example

---

azuread/resource_application.go
azuread/resource_application_test.go
website/docs/r/application.html.markdown

azuread_application - support for the public_client property

---

azuread/resource_application_password.go

azuread_application_password: fix incorrect conflicts with

---

examples/service_principal/basic/main.tf
examples/service_principal/create-for-rbac/main.tf

Hi 👋 ,
I noticed `random_string` was used in the examples. Thought it might be helpful to use `random_password` instead. I believe @katbyte is maybe the person to ping?
Thanks!

Uses random_password resource for sp examples

---

website/docs/d/application.html.markdown
website/docs/r/application.html.markdown

Adds missing docs to support #159 implementation

azuread_application  - Add Missing Documentation for Owner Arguments

---

azuread/resource_group_member.go

azuread_group_member - mark as missing when member cannot be found

---

azuread/helpers/graph/credentials.go
azuread/resource_application_password.go

azuread_application_password & azuread_service_principal_password - validate length < 863

---

azuread/helpers/graph/user.go

data.azuread_user[s] - use equals insteadof startsWith when finding users by mailNickname

---

CHANGELOG.md

changelog: note breaking change for azuread_application.oauth2_permissions

---

azuread/helpers/graph/group.go
azuread/resource_group.go

Also tidy up group related error messages
Fixes: #220

azuread_group: wait for replication before adding owners/members

---

.teamcity/components/build_components.kt
.teamcity/components/vcs_root.kt
README.md
website/docs/index.html.markdown

This PR was created to update all references from 'master' to 'main' in this repo.<br /><br />The following paths have been excluded: '[vendor/ GNUmakefile .git/ go.mod go.sum]'<br /><br />**NOTE**: This PR was generated automatically. Please take a close look before approving and merging!

Update References from master to main

---

internal/services/applications/application_resource.go
internal/services/applications/application_resource_test.go
internal/services/groups/group_resource_test.go

Also update tests
Closes: #383

Bugfix: set displayName correctly when creating/updating applications

---

examples/application/main.tf
examples/create-for-rbac/main.tf

Updates `examples/application/main.tf` from `name` which is depreciated to `display_name`

Update `examples/application` name to display_name

---

docs/resources/service_principal_password.md

Fix import example for azuread_service_principal_password

---

docs/resources/user.md
internal/services/users/user_resource.go
internal/services/users/user_resource_test.go
internal/validate/strings.go

Allow creation of guests users in azure active directory.
Refers issues #307 and #41

added support for guest users

---

docs/resources/group.md

Company Administrator and User Account Administrator roles don't exist anymore. It should be Groups Administrator now.

Documentation fix for azuread_group

---

docs/resources/application.md

Docs: Use Azure CLI querying to filter app IDs instead of powershell command

---

docs/resources/application.md
examples/application/locals.tf
examples/application/main.tf
examples/create-for-rbac/main.tf

Also update deprecated properties in examples
Resolves: #442

Improve docs around scope IDs for applications

---

docs/guides/microsoft-graph.md
internal/services/applications/application_data_source.go
internal/services/applications/application_data_source_test.go
internal/services/serviceprincipals/service_principal_data_source.go

- Also match some more UUIDs case insensitively as they should be
Fixes: #369

data.azuread_application: match display_name case insensitively

---

internal/services/applications/application_resource_test.go
internal/validate/uri.go

Applications: allow redirect URIs with schema "ms-appx-web"

---

internal/services/applications/applications.go

Nil checking to prevent crashes in block expand/flatten handling for applications

---

docs/resources/service_principal.md

Note in docs clarifying unsupported permission for service principals

---

internal/services/groups/group_resource.go

Bugfix: only specify the calling principal ID once when creating a group

---

docs/data-sources/service_principal.md
docs/data-sources/service_principals.md
docs/data-sources/users.md
internal/services/serviceprincipals/registration.go
internal/services/serviceprincipals/service_principal_resource_test.go
internal/services/serviceprincipals/service_principals_data_source.go
internal/services/serviceprincipals/service_principals_data_source_test.go

New data source: azuread_service_principals

---

.teamcity/components/project.kt
docs/resources/conditional_access_policy.md
internal/services/conditionalaccess/client/client.go
internal/services/conditionalaccess/conditional_access_policy_resource.go
internal/services/conditionalaccess/conditional_access_policy_resource_test.go
internal/services/conditionalaccess/registration.go

Based on the work in https://github.com/hashicorp/terraform-provider-azuread/pull/430 refactored to work with https://github.com/hashicorp/terraform-provider-azuread/pull/461 and also adding session controls and a few other attributes.
Let me know if you what you think and I'll crack on with the documentation
Thanks!
Closes: #348

Add Conditional Access Policy Support

---

docs/resources/application.md
internal/services/applications/application_resource.go
internal/services/applications/application_resource_test.go
internal/services/applications/migrations/application_resource.go
internal/services/invitations/invitation_resource.go
internal/services/serviceprincipals/service_principal_resource.go
internal/validate/uri.go
internal/validate/uri_test.go

azuread_application Allow URNs to be specified for web redirect URIs

---

docs/guides/microsoft-graph.md
docs/index.md
internal/provider/provider.go

Also clarify the supported cloud environment names
Closes: #583

Document breaking change to `group_membership_claims` for applications in v2.0

---

docs/resources/directory_role.md
docs/resources/directory_role_member.md

Corrections for azuread_directory_role / azuread_directory_role_member docs

---

docs/resources/application_password.md
docs/resources/service_principal_password.md
internal/services/applications/application_password_resource.go
internal/services/serviceprincipals/service_principal_password_resource.go

Document `keepers` property for application and service principal passwords

---

internal/services/directoryroles/directory_role_resource.go

Nil checking for directory role template

---

internal/services/serviceprincipals/service_principal_resource_test.go
internal/services/serviceprincipals/serviceprincipals.go

Bugfix: allow service principal with no features / all features disabled

---

.gitignore
docs/guides/microsoft-graph.md
docs/index.md
docs/resources/service_principal.md
docs/resources/user.md

Hello maintainers 👋🏼 
This PR fixes a few typos I came across while building some resources.
Happy Doctober!

fixes typos

---

docs/resources/group.md

Document additional permissions for `azuread_group.assignable_to_role` property

---

internal/services/groups/group_resource.go
internal/services/groups/group_resource_test.go

Bugfix: removal of all group members is ignored

---

internal/services/applications/application_resource.go
internal/services/applications/application_resource_test.go

azuread_application: Allow URNs for public_client redirect URIs

---

internal/services/conditionalaccess/conditional_access_policy_resource.go

Bugfix: nil check in diffsuppress func for conditional_access_policy

---

internal/services/applications/validate/tokens.go

azuread_application: Scope/Role validation for magic string "User"

---

internal/services/applications/validate/tokens.go

This reverts commit af740a7a5e3360aba46a1e754902d2b510f6bc0f.
Fixes: #755

Revert "azuread_application: Scope/Role validation for magic string "User"

---

scripts/release.sh

Improvements to release script:
- Check for clean working tree
- Run tests prior to release prep

Improve release script

---

internal/services/serviceprincipals/service_principal_data_source.go
internal/services/serviceprincipals/service_principal_data_source_test.go

Bugfix: raise error when multiple results are found for `azuread_service_principal` data source

---

docs/resources/conditional_access_policy.md

The previous example had syntax which was not valid. This PR updates the example to be a working example which can be used by copy-pasting into a .tf file.

Updated Conditional Access Policy documentation

---

internal/helpers/consistency.go

Bugfix: nil check the result of WaitForUpdateWithTimeout

---

internal/services/users/user_resource.go
internal/services/users/user_resource_test.go

azuread_user: user_principal_name should not be ForceNew

---

docs/guides/azure_cli.md
docs/guides/managed_service_identity.md
docs/guides/service_principal_client_certificate.md
docs/guides/service_principal_client_secret.md
docs/guides/service_principal_oidc.md
docs/index.md
internal/provider/provider.go
internal/provider/provider_test.go

Closes #803 
@manicminer here's the implementation for the AzureAD provider. https://github.com/manicminer/hamilton/releases/tag/v0.40.0 added this capability for the authentication method

Support for OIDC Authentication

---

docs/resources/claims_mapping_policy.md

Docs: Policy.Read.All role is required for azuread_claims_mapping_policy

---

docs/resources/directory_role_assignment.md
internal/services/directoryroles/directory_role_assignment_resource.go
internal/services/directoryroles/directory_role_assignment_resource_test.go

Also rename these properties, with deprecation path:
- `app_scope_object_id` to `app_scope_id`
- `directory_scope_object_id to `directory_scope_id`

Bugfix: fix a bug with scoped role assignments and fix incorrect schema validation

---

internal/services/users/user_resource.go

Bugfix: Only set `show_in_address_list` when changed in config as it is a potentially read-only attribute

---

internal/services/directoryroles/directory_role_assignment_resource.go

azuread_directory_role_assignment: fix a bug where `directory_scope_id` was not effectively optional

---

docs/resources/application_password.md

As per issue: https://github.com/hashicorp/terraform-provider-azuread/issues/848

Update application_password.md to reflect 'recreate resource' for display_name field.

---

docs/resources/group.md

Docs: azuread_group.dynamic_membership.rule is required, not optional

---

docs/resources/conditional_access_policy.md

Added Office365 as an option for included_applications.

Docs: Office365 in included_applications and excluded_applications

---

docs/resources/conditional_access_policy.md

`AllTrusted` can also be set on `excluded_locations`.

Docs: Add 'AllTrusted' as an option for 'excluded_locations'

---

docs/resources/application_certificate.md
docs/resources/service_principal_certificate.md

Docs: explain default values for start_date for certificate resources

---

docs/resources/service_principal_claims_mapping_policy_assignment.md

Docs: Policy.Read.All role is required for claim mapping

---

docs/resources/application.md

Solves https://github.com/hashicorp/terraform-provider-azuread/issues/920

Clarify the least privilege permissions needed for the azuread_application

---

internal/services/groups/group_resource_test.go
internal/validate/mail.go

azuread_group: mail_nickname can contain a period (.)

---

internal/services/serviceprincipals/service_principal_delegated_permission_grant_resource.go

azuread_delegated_permission_grant - fix bad existence check in read func

---

internal/services/groups/group_resource.go

azuread_group: set the display name correctly on creation, and patch afterwards for consistency checks

---

docs/resources/application.md
docs/resources/service_principal.md

azuread_application, azuread_service_principal: docs note to clarify tags usage

---

internal/services/applications/validate/tokens.go
internal/services/applications/validate/tokens_test.go

Applications: support app role values up to 249 characters

---

internal/services/serviceprincipals/client/client.go

Bugfix: synchronization only in beta API

---

docs/data-sources/group.md
docs/resources/group.md
internal/services/groups/group_data_source.go
internal/services/groups/group_data_source_test.go
internal/services/groups/group_resource.go
internal/services/groups/group_resource_test.go

Fixes #934
Depends on https://github.com/manicminer/hamilton/pull/199

Add group writeback functionality

---

docs/resources/access_package_assignment_policy.md
internal/services/identitygovernance/access_package_assignment_policy_resource.go

Tidy up docs for access_package_assignment_policy

---

internal/helpers/credentials.go
internal/services/serviceprincipals/service_principal_token_signing_certificate_resource.go

Bugfix: nil check when reading service principal token signing certificate data

---

docs/resources/group.md

azuread_group: update doc to clarify `assignable_to_role`

---

docs/data-sources/application_published_app_ids.md

data.azuread_application_published_app_ids: fix broken link in docs

---

.github/workflows/acctest-oidc.yaml
.github/workflows/depscheck.yaml
.github/workflows/docs-lint.yaml
.github/workflows/golint.yaml
.github/workflows/issue-comment-created.yaml
.github/workflows/issue-opened.yaml
.github/workflows/link-milestone.yaml
.github/workflows/lock.yaml
.github/workflows/milestone-closed.yaml
.github/workflows/pull-request.yaml
.github/workflows/release.yaml
.github/workflows/teamcity-test.yaml
.github/workflows/tflint.yaml
.github/workflows/thirty-two-bit.yaml
.github/workflows/unit-test.yaml
.github/workflows/validate-examples.yaml

Tooling: pin all GitHub workflows

---

docs/resources/administrative_unit.md

Fix a documentation typo on ***visibility*** replaced by ***hidden_membership_enabled***

Fix azuread_administrative_unit documentation

---

docs/resources/conditional_access_policy.md
internal/services/conditionalaccess/conditional_access_policy_resource.go
internal/services/conditionalaccess/conditional_access_policy_resource_test.go
internal/services/conditionalaccess/conditionalaccess.go

Adds support for `service_principal_risk_levels`. 
Updated tests.
Updated documentation.

`azuread_conditional_access` - add support for `service_principal_risk_levels`

---

docs/data-sources/named_location.md
docs/resources/named_location.md
internal/services/conditionalaccess/named_location_data_source.go
internal/services/conditionalaccess/named_location_data_source_test.go
internal/services/conditionalaccess/named_location_resource.go
internal/services/conditionalaccess/registration.go

Also, fix a bug that prevented deletion of an IP Named Location that was marked as trusted.
Closes: #1112

New data source: `azuread_named_location`

---

docs/resources/access_package_assignment_policy.md
internal/services/identitygovernance/access_package_assignment_policy_resource.go

azuread_access_package_assignment_policy: support `Manager` value for `review_type`

---

docs/resources/authentication_strength_policy.md
internal/services/conditionalaccess/client/client.go
internal/services/conditionalaccess/conditional_access_policy_resource_test.go
internal/services/conditionalaccess/registration.go
internal/services/policies/authentication_strength_policy_resource.go
internal/services/policies/authentication_strength_policy_resource_test.go
internal/services/policies/client/client.go
internal/services/policies/registration.go

Incldued a second example which includes all of the possible allowed_combinations.
Covers Issue #1216

Issue: 1216 - Updated documentation to include second example

---

docs/resources/application.md
docs/resources/application_redirect_uris.md

docs: fix import examples for `azuread_application` and `azuread_application_redirect_uris`

---

internal/services/identitygovernance/access_package_assignment_policy_resource_test.go
internal/services/identitygovernance/identitygovernance.go

bugfix: correctly handle missing `question` properties for azuread_access_package_assignment_policy

---

.goreleaser.yml

Update .goreleaser.yml to include LICENSE

Update .goreleaser.yml to include LICENSE

---

internal/services/users/user_resource.go

Change validation of employeeType
Checked for input of 64 characters or less

Change validation of employeeType

---

internal/services/conditionalaccess/conditional_access_policy_resource_test.go
internal/services/conditionalaccess/conditionalaccess.go

Reverts hashicorp/terraform-provider-azuread#1417

Revert "bugfix: ensure `sessionControls.isEnabled: true` when specifying `sign_in_frequency_interval = "everyTime"`"

---

docs/resources/group.md
docs/resources/user.md

Update the import statements for the user and group resources to the format required since v3.
Relates #1508

Update import documentation for user and group

---

internal/services/applications/application_registration_resource.go

I've stumbled across this typo so i thought it woud not hurt to fix it :)

Fix error message typo

---

internal/services/conditionalaccess/conditionalaccess.go

`azuread_conditional_access_policy` - fix potential panic in expanding `conditions`

---

docs/resources/group_member.md

Updates example usage to be match the attributes of the azuread_group and azuread_user resources.

[Docs] azuread_group_member - update example usage code block

---

internal/services/identitygovernance/identitygovernance.go

Potential fix for https://github.com/hashicorp/terraform-provider-azuread/issues/1535

fix: azuread_access_package_assignment_policy fails with alternative_approver

---

.teamcity/components/settings.kt
internal/acceptance/data.go
internal/acceptance/helpers/is_not_resource_action.go
internal/acceptance/testcase.go
internal/acceptance/testing.go
internal/helpers/consistency/consistency.go
internal/services/administrativeunits/administrative_unit_role_member_resource_test.go
internal/services/applications/application_fallback_public_client_resource_test.go
internal/services/applications/application_resource.go
internal/services/applications/application_resource_test.go
internal/services/conditionalaccess/named_location_resource.go
internal/services/directoryobjects/directory_object_data_source_test.go
internal/services/groups/group_data_source_test.go
internal/services/groups/group_resource.go
internal/services/groups/group_resource_test.go
internal/services/serviceprincipals/service_principal_data_source_test.go
internal/services/serviceprincipals/service_principal_resource_test.go
internal/services/userflows/user_flow_attribute_resource.go
internal/services/userflows/user_flow_attribute_resource_test.go

Test fixes across all services

`testing` - post 3.0 test cleanup
