hashicorp/terraform-provider-azuread

azuread/data_application.go
azuread/helpers/tf/marshall.go
azuread/resource_application.go
azuread/resource_application_test.go

azuread_application: correctly read reply URL's from SDK

---

azuread/config.go
azuread/data_source_group.go
azuread/data_source_group_test.go
azuread/provider.go
azuread/resource_group.go
azuread/resource_group_test.go
website/azuread.erb
website/docs/d/group.html.markdown
website/docs/r/group.markdown

This PR adds a new resource and data source for Azure Active Directory groups.
The is based on the PR terraform-providers/terraform-provider-azurerm#1839
```hcl
// This creates a new Azure AD group with the display name "my_group"
resource "azuread_group" "my_group" {
name = "my_group"
}
// This queries an Azure AD group by ID
data "azuread_group" "my_group_by_id" {
object_id = "78722cfc-8946-11e8-95f1-2200ec79ad01"
}
// This queries an Azure AD group by Name
data "azuread_group" "my_group_by_name" {
name = "my_group"
}
```
The following attributes are exported:
* `id` - The Object ID for the Azure AD Group.
* `name` - The Display Name for the Azure AD Group.

New resource & data source 'azuread_group'

---

.golangci.yml

Was not enabled during the switch to golangci due to a bug in the version of goimports they used. As it's been fixed re-enabling it.

linting: enable goimports

---

azuread/resource_service_principal_password.go
azuread/resource_service_principal_password_test.go
website/docs/r/service_principal_password.html.markdown

azuread_service_principal_password: add the end_date_relative property

---

azuread/resource_application.go
azuread/resource_application_test.go

Use TypeSet for reply_urls to ignore order.

Ignore order for reply_urls

---

azuread/resource_user.go
website/docs/r/user.html.markdown

More info here:
https://techcommunity.microsoft.com/t5/Azure-Active-Directory-Identity/Removal-of-the-16-character-limit-for-passwords-in-Azure-AD/ba-p/565275

Increase maximum password length from 16 to 256

---

website/docs/r/service_principal.html.markdown

appId was missing in the Service Principal creation output, added it.

Added appId output to the documentation - esp. important for AKS

---

azuread/provider.go
azuread/resource_application.go
azuread/resource_service_principal.go

enhance application and SP replication wait

---

azuread/data_application.go
azuread/data_domains.go
azuread/data_group.go
azuread/data_group_test.go
azuread/data_user.go
azuread/data_user_test.go
website/docs/d/group.html.markdown
website/docs/d/service_principal.html.markdown
website/docs/d/user.html.markdown

This allows looking up by object_id.
As well fixes a bug where id there are multiple groups or users found for a given name it will now error instead of only returning the first.

data.azuread_[group|user]: add lookup by object_id

---

azuread/data_service_principal.go
azuread/data_user_test.go
azuread/resource_application.go
azuread/resource_application_password.go
azuread/resource_application_password_test.go
azuread/resource_service_principal.go
azuread/resource_service_principal_password_test.go
azuread/resource_service_principal_test.go
azuread/resource_user_test.go
website/docs/r/application_password.html.markdown

fixes #106 
given there is both `application.object_id` and `application.application_id` this should bring some clarity and hopefully prevent confusion.

azuread_application_password: deprecate application_id in favour of application_object_id

---

azuread/data_application.go
azuread/data_application_test.go
azuread/data_service_principal.go
azuread/data_service_principal_test.go
azuread/helpers/graph/application.go
azuread/resource_application.go
website/docs/d/application.html.markdown
website/docs/d/service_principal.html.markdown

Use case is to read roles from *"Microsoft Applications"*, for example:
```hcl
data "azuread_service_principal" "main" {
display_name = "Microsoft Graph"
}
output "app_roles" {
value = data.azuread_service_principal.main.app_roles
}
```

azuread_application & azuread_service_principal: export the `app_roles` property

---

.hashibot.hcl

This file configures hashibot
Once this PR is merged, as well as the other open PRs to achieve "parity" with what is currently running for the bot in production, I can push the new bot to production. That is to say there is no implication by hitting merge at the moment, but soon this is the place to configure aws provider specific bot behaviors. You can also override/disable some of the global behaviors that are defined here:
https://github.com/terraform-providers/.hashibot/blob/master/.hashibot.hcl
Documentation on this system is in progress.

capture current hashibot config

---

azuread/helpers/validate/url.go
azuread/helpers/validate/url_test.go
azuread/resource_application.go

As per the Azure Portal, the following schemes are allowed for application ID URIs:
- `https`
- `api`
- `urn`
- `ms-appx`
This change allows these URI schemes to be used, and also retains the already-allowed `http` scheme for compatibility (since that was already allowed, [then disallowed](https://github.com/terraform-providers/terraform-provider-azurerm/pull/1960), [then allowed again](https://github.com/terraform-providers/terraform-provider-azurerm/pull/2320) in the azurerm provider).
Tests are passing locally for me but I haven't run acceptance tests.

azuread_application: Allow all valid app identifier URI schemes

---

azuread/helpers/graph/group.go
azuread/helpers/slices/slices.go
azuread/provider.go
azuread/resource_group.go
azuread/resource_group_member.go
azuread/resource_group_member_test.go
azuread/resource_group_test.go
website/azuread.erb
website/docs/r/group.markdown
website/docs/r/group_member.markdown

This PR continues where #63 left off. In addition to fixing the comments pointed out in the review, it introduces support for adding members to a group.
Go is not my main language and I'm not that familiar with Terraform so don't be afraid to do a proper review :-)

Resource: 'azuread_group_member'

---

azuread/resource_application_password.go
azuread/resource_service_principal_password.go

Hi @katbyte 
This PR waits on Password replication, same as done in #93 for Application and service principal.
Please note that I have not run the integration tests as get a workable AAD, may be bit complex for me.

Wait on password replication

---

website/docs/auth/service_principal_configuration.html.markdown

To get all the Service Principals from `Get-AzureADServicePrincipal` you need to add the `-All $true` flag.
On a tenant with a lot of service principals you need this flag to retrieve all of them.

Add -All $true to Get-AzureADServicePrincipal

---

azuread/resource_service_principal.go
azuread/resource_service_principal_test.go
website/docs/r/service_principal.html.markdown

This adds support for setting the `AppRoleAssignmentRequired` property on a service principal.
I'm not sure if I implemented the update function correctly, but since it was not already there I think I had to create it.

azuread_service_principal - support for the AppRoleAssignmentRequired property

---

website/docs/r/group_member.markdown

The import usage for the `azuread_group_member` resource doesn't work as documented with error 
``` * import azuread_group_member.xxx result: 000-000-000/111-111-111: azuread_group_member.xxx: Unable to parse ID: Unable to parse Member ID: Object Resource ID should be in the format {objectId}/{keyId} - but got "000-000-000/111-111-111``` but works with `terraform import azuread_group_member.test 00000000-0000-0000-0000-000000000000/member/11111111-1111-1111-1111-111111111111`

Update azuread_group_member import usage snippet

---

azuread/resource_application.go
azuread/resource_application_test.go

I haven't run the acceptance tests, but I couldn't find any documentation saying that HTTP shouldn't work.

azuread_application: homepage now accepts HTTP/HTTPS

---

azuread/data_user.go
azuread/resource_user.go
azuread/resource_user_test.go
website/docs/d/user.html.markdown
website/docs/r/user.html.markdown

Setting usage location is required for users that will be assigned licenses (e.g. Azure Active Directory Premium P1/2 licenses) due to legal requirement to check for availability of services in countries.

azuread_user - support for the `usage_location` property

---

website/azuread.erb
website/docs/guides/azure_cli.html.markdown
website/docs/guides/managed_service_identity.html.markdown
website/docs/guides/service_principal_client_certificate.html.markdown
website/docs/guides/service_principal_client_secret.html.markdown
website/docs/guides/service_principal_configuration.html.markdown
website/docs/index.html.markdown
website/docs/r/service_principal.html.markdown

And add subcategories
These changes are required to ensure that docs for this provider display
correctly on registry.terraform.io.
For more information about how documentation is rendered on the Terraform Registry, please see this reference: [Terraform Registry - Provider Documentation](https://www.terraform.io/docs/registry/providers/docs.html).
**This should not be merged until a future PR on hashicorp/terraform-website is ready to merge with redirects for these moved files.**

website: Move auth guides to guides/ folder

---

website/azuread.erb
website/docs/d/groups.html.markdown

- looks like website sidebar documentation link missed in https://github.com/terraform-providers/terraform-provider-azuread/pull/120,

azuread_groups - sidebar and doc fix

---

README.md

Based on the version of go in [go.mod](https://github.com/brunhil/terraform-provider-azuread/blob/update-readme-goversion/go.mod), we should be stating we require version 1.13.

Update go version in docs

---

azuread/resource_application_password_test.go
azuread/resource_service_principal_password_test.go
website/docs/r/application_password.html.markdown
website/docs/r/service_principal_password.html.markdown

Fixes issue in tests and documentation where the tests uses 2020-01-01 as a date meant to be in the future. Have changed this to 2099 to prevent this issue from happening again.

Fixes #201. Changed date to 2099 to prevent issue.

---

azuread/resource_application.go

The Azure Portal does not enforce the `identifier_uris` / `entity id` to be in a valid URL format. 
There is also a 3rd party gallery app called box which required this to be `box.net` which fails under the current func `validate.URLIsAppURI `
Documentation around said 3rd party app which requires a non url based value can be found [here](https://community.box.com/t5/How-to-Guides-for-Admins/Setting-Up-Single-Sign-On-SSO-for-your-Enterprise/ta-p/1263)
You can also this see this is true and valid via official Microsoft Docs [here](https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/box-tutorial#configure-azure-ad-sso)

azuread_application - Removed unrequired validation

---

website/docs/d/group.html.markdown

I saw that exporting group owners is implemented, but documentation is not synched with implementation.
fixes #196

Update data_group outputs in docs (#196)

---

azuread/data_user.go
azuread/resource_user.go
website/docs/d/user.html.markdown
website/docs/r/user.html.markdown

Adds a couple on premises values required for our use:
- on_premises_sam_account_name
- on_premises_user_principal_name
Documented here: https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0
Should exist within Azure SDK: https://github.com/Azure/azure-sdk-for-go/blob/master/services/graphrbac/1.6/graphrbac/models.go#L3756

azuread_user - add `onpremises_sam_account_name` and `onpremises_user_principal_name`

---

azuread/data_user.go
azuread/helpers/p/p.go
azuread/resource_user.go
azuread/resource_user_test.go
go.sum
website/docs/d/user.html.markdown
website/docs/r/user.html.markdown

azuread_user support for immutable_id property

---

azuread/resource_group.go

Fixed func resourceGroupCreate. From now you can pass your object_id to the owner list
(fixes #212)

azuread_group - owners is now additive on creation allowing existing owner to be in owners list

---

CHANGELOG.md
azuread/data_application.go
azuread/resource_application.go
azuread/resource_application_test.go
website/docs/d/application.html.markdown
website/docs/r/application.html.markdown

azuread_application - add logout_url & fix owner add/delete order

---

azuread/config.go
azuread/data_client_config.go
azuread/data_client_config_test.go
azuread/helpers/graph/credentials.go
azuread/provider.go
azuread/resource_application_password.go
website/allowed-subcategories
website/azuread.erb
website/docs/d/client_config.html.markdown

New Data Source: azuread_client_config

---

azuread/data_application_test.go
azuread/resource_application.go
azuread/resource_application_test.go
website/docs/r/application.html.markdown

Added support to use ApplicationGroup as a valid group_membership_claims option. 
Updated docs to include this also 
Issue detailing this change can be found here https://github.com/terraform-providers/terraform-provider-azuread/issues/239

Added support for ApplicationGroup

---

azuread/resource_service_principal.go

You can update a service principal's tags without destroy it using the graph API or powershell, so there is no reason why this provider should force a new Service Principal

Removed forceNew flag from resource_service_principal tags

---

website/docs/d/application.html.markdown

`public_client` was added to the azuread provider [here](https://github.com/terraform-providers/terraform-provider-azuread/pull/121) but the current documentation doesn't include it

document application public_client property

---

azuread/resource_application.go
azuread/resource_application_test.go
website/docs/r/application.html.markdown

Enable setting OAuth 2.0 permission scopes for an AAD application.
If omitted, will be computed from scopes defined out of band.
If specified, will replace any existing scopes configured for an application.
If specified as empty value, will remove any existing scopes from an application.
Thanks to @jorgecarleitao for initial work on #187
Fixes: #73, #162
Replaces: #187

application: support for setting oauth2_permissions

---

azuread/helpers/graph/credentials.go
azuread/resource_application_password.go
azuread/resource_application_password_test.go
azuread/resource_service_principal_password.go
azuread/resource_service_principal_password_test.go
website/docs/r/application_password.html.markdown
website/docs/r/service_principal_password.html.markdown

This is the same description field yielded by the corresponding Portal page. Although the API exposes it as `customKeyIdentifier` this term doesn't seem to be exposed to users.
Fixes: #95

Support descriptions for azuread_application_password / azuread_service_principal_password

---

azuread/data_groups.go
azuread/data_groups_test.go
website/docs/d/groups.html.markdown

Support empty lists for the `names` and `object_ids` arguments, in which case no results will be returned. Aims to support the use case of the data source in a module where the input variable may be empty.
Thanks to @jpreese for the suggestion and implementation
Replaces: #231

data.azuread_groups: support empty list for names/object_ids arguments

---

azuread/data_users.go
azuread/data_users_test.go
website/docs/d/users.html.markdown

Support empty lists for the `user_principal_names`, `object_ids` and `mail_nicknames` arguments, in which case no results will be returned. Aims to improve reusability where the data source is used in a module where the input variable(s) may be empty.

 data.azuread_users: support empty search lists

---

azuread/helpers/graph/credentials.go
website/docs/r/application_password.html.markdown

As per API, perform validation at plan time. Also fix up usage example for `azuread_application_password`.
```
azuread_application_password.test: Creating...
azuread_service_principal_password.test: Creating...
Error: Error generating Service Principal Credentials for Object ID "11b9ba63-8800-4644-aa21-a427ebf176a8": one of `end_date` or `end_date_relative` must be specified
on sp.tf line 5, in resource "azuread_service_principal_password" "test":
5: resource "azuread_service_principal_password" "test" {
Error: Error generating Application Credentials for Object ID "cf34834b-b0ca-490a-9037-fe1002906768": one of `end_date` or `end_date_relative` must be specified
on sp.tf line 11, in resource "azuread_application_password" "test":
11: resource "azuread_application_password" "test" {
``` …

End date validation for azuread_application_password / azuread_service_principal_password

---

azuread/helpers/graph/credentials.go
azuread/provider.go
azuread/resource_application_certificate.go
azuread/resource_application_certificate_test.go
azuread/resource_application_password.go
azuread/resource_application_password_test.go
azuread/resource_service_principal_certificate.go
azuread/resource_service_principal_certificate_test.go
azuread/resource_service_principal_password.go
azuread/resource_service_principal_password_test.go
website/azuread.erb
website/docs/r/application_certificate.html.markdown
website/docs/r/service_principal_certificate.html.markdown

New resources: azuread_application_certificate and azuread_service_principal_certificate

---

azuread/data_client_config.go
azuread/data_client_config_test.go
azuread/provider.go
azuread/provider_test.go
azuread/resource_application_certificate_test.go
azuread/resource_service_principal_certificate_test.go
website/docs/guides/azure_cli.html.markdown
website/docs/guides/managed_service_identity.html.markdown
website/docs/guides/service_principal_client_certificate.html.markdown
website/docs/guides/service_principal_client_secret.html.markdown
website/docs/guides/service_principal_configuration.html.markdown

Stop requiring a subscription ID to be configured (though still allow it for compatibility)
- See 44829f2621da31096fe4b06d3ca810631dc078b2
Configuration guide updates
- Walkthroughs reflect current portal experience
- Amend guidance on AAD permissions
- Document some common AAD roles and API scopes
- Note on subscription ID
- Remove references to configuring subscriptions
Also fix up certificate related tests by shortening validity period to 6 months
**DEPRECATION WARNING**
The `subscription_id` attribute will be removed from the `azuread_client_config` data source in v1.0. The subscription ID here is only an echo of the subscription ID supplied by the user and there is no possible way to use it currently elsewhere in the provider. Configurations can switch over to the …

Stop requiring subscription_id and update configuration guides

---

azuread/data_application.go
azuread/data_application_test.go
azuread/data_group_test.go
azuread/data_groups_test.go
azuread/data_service_principal_test.go
azuread/data_user_test.go
azuread/data_users_test.go
azuread/resource_application_certificate_test.go
azuread/resource_application_password_test.go
azuread/resource_group_member_test.go
azuread/resource_service_principal_certificate_test.go
azuread/resource_service_principal_password_test.go
azuread/resource_service_principal_test.go
website/docs/d/application.html.markdown
website/docs/d/domains.html.markdown
website/docs/r/application_certificate.html.markdown
website/docs/r/application_password.html.markdown
website/docs/r/group.markdown
website/docs/r/group_member.markdown
website/docs/r/service_principal.html.markdown
website/docs/r/service_principal_certificate.html.markdown
website/docs/r/service_principal_password.html.markdown
website/docs/r/user.html.markdown

* Update documentation examples and acceptance test configs to use Terraform 0.12 style expressions
* Support the `application_id` argument for `data.azuread_application` for locating applications

Syntax updates for Terraform 0.12, support application_id argument on data.azuread_application

---

website/docs/r/application_password.html.markdown

For beginners its quite usefull to know that application password is primarily named 'Client secrets' in the Azure management portal. It is stated that 'Client secrets' can be referred to as application password, but if you are not that familiar with the azure platform this might help someone out.
From the Azure portal:

Comment about client secrets

---

azuread/helpers/graph/application.go
azuread/helpers/graph/group.go
azuread/resource_application.go
azuread/resource_application_test.go
azuread/resource_group.go
azuread/resource_group_test.go
website/docs/r/application.html.markdown
website/docs/r/group.markdown

- New property `prevent_duplicate_names`, defaults to false
- When true, searches for an existing application / group and errs if one found having the same name
- For applications, also performs the check on update
Closes: #182, #200

azuread_application & azuread_group: Duplicate name detection

---

azuread/helpers/graph/group.go
azuread/helpers/graph/replication.go
azuread/resource_group.go

1. Attempt up to 10 times to add a group member with fixed 2 second backoff
2. Ensure 10 affirmative responses when retrieving group members after adding
3. Attempt up to 10 times to remove a group member with fixed 2 second backoff
4. Ensure 10 affirmative responses when retrieving group members after removing
**Fixes:**
> Error adding group member "62a54f8c-eef7-4106-9989-aa9018f46a98" to Azure AD Group with ID "d8c4d6c5-7d04-4865-85a6-cf311f1a619c": graphrbac.GroupsClient#AddMember: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Request_BadRequest","date":"2020-06-17T02:03:42","message":{"lang":"en","value":"One or more added object …

azuread_group: remediate replication delays when adding/removing group members

---

azuread/data_users.go
azuread/data_users_test.go
website/docs/d/users.html.markdown

Return all user data in `users` parameter aray
* Add users parameter - an array of users which mirrors that of the user
data source. This allows for additional validation of users - such as
checking whether the account is enabled.
Allow user lookup to gracefully fail
* Add graceful_errors parameter to allow user lookup to gracefully fail.
This allows only users which were successfully looked up to return. The
data source will still result in an error if no users were returned.
Documentation updated to include the two new parameters.
Add missing MailNickname validation logic

Allow for graceful handling of errored users within users data source

---

azuread/resource_application.go
azuread/resource_application_test.go
website/docs/r/application.html.markdown

Roles (appRoles) and scopes (oauth2Permissions) exposed by an application share a common namespace where the values cannot overlap. This change adds some local validation to screen for these before PATCHing an application.
Changes the resulting error message from this:
```
Error: patching Azure AD Application with ID "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee": graphrbac.ApplicationsClient#Patch: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Request_BadRequest","date":"2020-06-09T10:06:21","message":{"lang":"en","value":"Request contains a property with duplicate values."},"requestId":"dab8185c-239f-44dd-8ca3-8bd13e3e67b3","values":[{"item":"Pr …
```

azuread_application: validate values for app_role and oauth2_permissions to screen for duplicates

---

azuread/data_user.go
azuread/data_user_test.go
azuread/data_users.go
azuread/data_users_test.go
azuread/helpers/graph/user.go

- Better test coverage in `data.azuread_user` and `data.azuread_users`.
- Prettier errors when users not found.
- Fix nil pointer dereference due to mishandling of search results (reported: https://github.com/terraform-providers/terraform-provider-azuread/pull/256#issuecomment-651645643)

Fix nil pointer dereference in data.azuread_users and improve test coverage

---

azuread/data_users.go

Fixes users lookup loop breaking when a user returns an error, rather than continuing. This resulted in a partially returned list of valid users.
Fixes issue reported in #289
CC @manicminer

Fix for users read lookup loop breaking rather than continuing

---

website/docs/index.html.markdown

Version 1.0.0 removed the `subscription_id` argument for configuring the azuread provider, which causes an error if you configured that previously. It was a bit confusing to reference the documentation and see that it was still an optional argument.
```
Error: Unsupported argument
on providers.tf line 37, in provider "azuread":
37:   subscription_id = var.azure-infra-subscription-id
An argument named "subscription_id" is not expected here.
```
This PR removes the reference to that configuration option in the website doc.

remove reference to subscription_id in provider doc

---

website/docs/guides/service_principal_configuration.html.markdown

There is a missing link in the [Service Principal Configuration documentation](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/service_principal_configuration#method-2-api-access-with-admin-consent), which made it a bit harder to read but still understandable. This change cleans up the broken link format rendered to users and make it more readable and usable.

Fix missing link in SP configuration documentation

---

internal/services/aadgraph/application_resource.go

application: Don't perform duplicate name check on update unless the name was changed

---

internal/services/aadgraph/user_data_source.go
internal/services/aadgraph/user_resource.go
internal/services/aadgraph/user_resource_test.go
website/docs/d/user.html.markdown
website/docs/r/user.html.markdown

azuread_user: additional fields for resource and data source

---

internal/services/aadgraph/application_resource.go
internal/services/aadgraph/application_resource_test.go

Enables removal of owners on existing applications, and creation of applications with no owners (by default a new application gets the creator assigned as a single owner).
Closes: #352 
Closes: #353

azuread_application: enable removal of owners

---

internal/clients/builder.go
internal/provider/provider.go
internal/services/configure_client.go
website/docs/d/application.html.markdown
website/docs/d/client_config.html.markdown
website/docs/d/domains.html.markdown
website/docs/d/group.html.markdown
website/docs/d/groups.html.markdown
website/docs/d/service_principal.html.markdown
website/docs/d/users.html.markdown
website/docs/guides/azure_cli.html.markdown
website/docs/guides/managed_service_identity.html.markdown
website/docs/guides/service_principal_client_certificate.html.markdown
website/docs/guides/service_principal_client_secret.html.markdown
website/docs/guides/service_principal_configuration.html.markdown
website/docs/index.html.markdown
website/docs/r/application_certificate.html.markdown
website/docs/r/application_password.html.markdown
website/docs/r/group.markdown
website/docs/r/service_principal_certificate.html.markdown
website/docs/r/service_principal_password.html.markdown

- Enable a custom partner ID
- Fix some typos
- Bring example configs up to date
- Present example AAD roles as a table
- Document the `metadata_host` provider attribute
- Add provider attributes for configuring partner ID
- Clarify that MSI authentication only works for the current tenant
Closes #349

Various documentation fixes and enable custom partner ID

---

internal/services/aadgraph/application_resource.go
internal/services/aadgraph/application_resource_test.go

Reverts #355 
Whilst we want to enable application owners to be empty at create time, this cannot be done whilst also having the ability to retain the default owner assigned by Azure AD.
With this fix, the following applies:
- Default application owner is retained at create time
- Default owner can be overridden with one or more specified owners
- Owners cannot be forced empty at create time
- Owners can be forced empty on subsequent applies, with the caveat that Terraform must detect a config change
Fixes #365

azuread_application: revert #355 but retain tests, must retain default application owner at create time

---

internal/services/aadgraph/application_resource.go
internal/services/aadgraph/application_resource_test.go
internal/services/aadgraph/graph/application.go

There are a set of small bugs which can occur by updating immediately after creating an application, mostly around the reliance on `d.GetChange()`, which is always true in this scenario.
This PR refactors the update logic for the `app_role` and `oauth2_permissions` properties into a helper function, and stops returning `applicationResourceUpdate()` at the end of `applicationResourceCreate()`. Additionally fixes up the setting of `prevent_duplicate_names` on read to avoid unwanted diffs, and adds regression test coverage for that attribute.
Sets `ConfigMode: schema.SchemaConfigModeAttr` on the `app_role` attribute to enable specifying an empty list in order to remove existing app roles. As with the other optional+computed attributes, this only works on update and if a config change is …

azuread_application: avoid update after create

---

docs/resources/application_certificate.md
docs/resources/service_principal_certificate.md
internal/helpers/aadgraph/credentials.go
internal/services/applications/application_certificate_resource_test.go
internal/services/serviceprincipals/service_principal_certificate_resource_test.go

For `azuread_application_certificate` and `azuread_service_principal_certificate` resources.
Adds an `encoding` property which defaults to "pem" and supports:
- `pem` - the currently supported PEM encoding
- `base64` - base64 encoded DER certificate
- `hex` - hexadecimal encoded DER certificate, i.e. as exported by `azurerm_key_vault_certificate`
Closes: #385

Support hexadecimal and base64 encoded DER certificates

---

docs/data-sources/group.md
docs/resources/group.md
internal/helpers/aadgraph/group.go
internal/services/groups/group_data_source.go
internal/services/groups/group_data_source_test.go
internal/services/groups/group_resource.go
internal/services/groups/groups_data_source.go

Adds `mail_enabled` and `security_enabled` to the resource and data source. Due to API limitations, only security groups can be created, so these are computed for now.
Closes: #391

azuread_group: add mail_enabled and security_enabled attributes

---

docs/data-sources/user.md
docs/resources/user.md
internal/services/users/user_data_source.go
internal/services/users/user_data_source_test.go

Also add documentation note to explain the problem with being forced to set a password for guest users.

data.azuread_user: export the user_type attribute

---

docs/resources/service_principal.md

The `name` in the `azuread_application` resource mentioned with the `azuread_service_principal` docs should be `display_name`.

📝 Fix wrong parameter in `azuread_application` resource

---

internal/services/applications/application_resource.go
internal/validate/uri.go
internal/validate/uri_test.go
internal/validate/url_test.go

Fixes #425 by refactoring the URL validation to support both URLs & URNs.
I looked for Go packages that do URN validation, and found [voicera/gooseberry urn#TryParseString](https://pkg.go.dev/github.com/voicera/gooseberry@v0.0.0-20181223025147-dc233900870c/urn#TryParseString) and [leodido/go-urn#Parse](https://pkg.go.dev/github.com/leodido/go-urn#Parse). Neither seemed worth adding as a dependency, so I used the simple validation logic from the former.

Support URNs properly

---

README.md

git clone URI is missing protocol prefix

Minor Documentation Correction: git clone URI should be a valid URI

---

.github/workflows/lock.yml
.hashibot.hcl

There is not an equivalent for the `release_commenter` behavior yet to fully remove the configuration (unless you are okay without it for now, then happy to just remove the whole thing 👍 ).

Migrate from GitHub HashiBot lock behavior to GitHub Actions

---

docs/index.md
internal/provider/provider.go

Provider schema validation raises a warning diagnostic for deprecated fields even if a property isn't present in configuration (or it's corresponding env var is also not set). This removes the Deprecation field from `metadata_host` and updates the documentation.
Closes #437

Bugfix: suppress spurious deprecation notice for `metadata_host` provider field even when not set

---

docs/guides/microsoft-graph.md
docs/resources/application_password.md
docs/resources/service_principal_password.md
internal/services/applications/application_password_resource_msgraph.go
internal/services/serviceprincipals/service_principal_password_resource_msgraph.go

- Don't allow `description` to be set in configuration when using MS Graph
- Clarify the situation regarding the field changes for `azuread_application_password` and `azuread_service_principal_password`
Closes: #438

Bugfix: error on password creation when `description` set for MS Graph

---

docs/data-sources/groups.md

This [commit](https://github.com/hashicorp/terraform-provider-azuread/commit/4bfce613d6260852e8f4d99bc54f8e49dc285a79#diff-20e1b0b3a19616f5586877bf83247b078abe90d7249d02222ba79751db540857) forgot to rename property names in other places this fixes it

docs/data-sources/groups.md: Fix property name that wasn't renamed

---

docs/guides/microsoft-graph.md

Double quotes are for interpolated strings, for constant strings, single quotes should be used, see https://github.com/PowerShell/PSScriptAnalyzer/blob/master/RuleDocumentation/AvoidUsingDoubleQuotesForConstantString.md
In this instance, not even a single quote is required as PowerShell knows that the `env` PSDrive only takes strings and converts the integer to a string for you

microsoft-graph.md: Simplify PowerShell command

---

docs/guides/microsoft-graph.md
internal/services/applications/application_app_role_resource.go
internal/services/applications/application_oauth2_permission_resource.go
internal/services/applications/application_oauth2_permission_scope_resource.go

Both the `azuread_application_app_role` and `azuread_application_oauth2_permission`
resources were added to the provider as a workaround for several bugs in our
implementations of the corresponding properties in the `azuread_application` resource.
- Both these properties (blocks) are TypeSet, and currently Optional + Computed,
which stems from API inconsistencies and (in the case of oauth2 permissions)
default values applied by the AAD Graph API.
- The `id` field in each of these blocks is Computed (read-only),
however there are use cases where it's necessary to be able to specify
this field. We couldn't make this field Optional + Computed inside a TypeSet
that is also Optional + Computed, due to an upstream limitation / bug.
We therefore introduced these virtual resources to enable users …

Deprecation notices for application_oauth2_permission{,_scope} and azuread_application_app_role resources

---

internal/services/applications/application_password_resource.go
internal/services/applications/application_resource.go
internal/services/applications/migrations/application_password_resource.go
internal/services/applications/migrations/application_resource.go
internal/services/serviceprincipals/migrations/service_principal_password_resource.go
internal/services/serviceprincipals/service_principal_password_resource.go

- Migrate `group_membership_claims` in `azuread_application` from a TypeString to a TypeSet
- Organize other state migrations into `migrations/` directory for each service
Fixes: #484

Add state migration for azuread_application to handle group_membership_claims type change

---

internal/services/applications/migrations/application_resource.go

- Add a migration for the `public_client` attribute to rename it to `fallback_public_client_enabled`

Add migration for public_client attribute

---

internal/services/applications/application_password_resource.go

Fix for #498 
- Decode CustomKeyIdentifier used by prior provider versions and use it as display_name if DisplayName is nil

When reading, use decoded CustomKeyIdentifier as display_name if DisplayName is nil

---

internal/services/applications/application_password_resource.go
internal/services/serviceprincipals/service_principal_password_resource.go

Source display_name from `CustomKeyIdentifier` field as per legacy API to prevent unintentional ForceNew after upgrade
(Same fix as implemented in #499 for `azuread_application_password`)

azuread_service_principal_password: fix for unintentional forcenew

---

docs/guides/service_principal_client_secret.md

The page references using a "Client Certificate" but it should read "Client Secret"

[docs] Fix typo in Service Principal/Client Secret doc

---

docs/data-sources/service_principal.md
docs/resources/service_principal.md
internal/services/serviceprincipals/service_principal_data_source.go
internal/services/serviceprincipals/service_principal_data_source_test.go
internal/services/serviceprincipals/service_principal_resource.go
internal/services/serviceprincipals/service_principal_resource_test.go
internal/services/serviceprincipals/serviceprincipals.go

service_principal: Support the `saml_single_sign_on` block with the `relay_state` property

---

docs/resources/user.md
internal/services/users/user_resource.go
internal/services/users/user_resource_test.go

Closes: https://github.com/hashicorp/terraform-provider-azuread/issues/136
@manicminer is this the kind of thing you had in mind? 
One thing I haven't checked is if both are true will graph always return them in that order or should we just check if the string contains `DisablePasswordExpiration`/`DisableStrongPassword` rather than going for an exact match

Support for password policies

---

docs/resources/conditional_access_policy.md
internal/services/conditionalaccess/client/client.go
internal/services/conditionalaccess/conditional_access_policy_resource.go
internal/services/conditionalaccess/conditional_access_policy_resource_test.go

Fixes https://github.com/hashicorp/terraform-provider-azuread/issues/568
Whilst testing this I initially started by commenting out the setting of `ApplicationEnforcedRestrictions` and `CloudAppSecurity` in `expandConditionalAccessSessionControls` which bizarrely started causing panics in `flattenConditionalAccessSessionControls`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xed80d0]
goroutine 691 [running]:
github.com/hashicorp/terraform-provider-azuread/internal/services/conditionalaccess.flattenConditionalAccessSessionControls(...)
/home/alexwilcox/go/src/github.com/hashicorp/terraform-provider-azuread/internal/services/conditionalaccess/conditional_access_policy_resource.go:573 …
```

Bugfix CA Policies

---

internal/services/applications/application_resource.go
internal/services/applications/applications.go
internal/services/groups/group_resource.go
internal/tf/pluginsdk.go

- Helper func for unknown plan-time strings
- Ensure `prevent_duplicate_names` checks don't falsely fail for unknown display names
Closes: #592

Ensure `prevent_duplicate_names` checks don't falsely fail for unknown display names

---

docs/data-sources/groups.md
internal/acceptance/check/that.go
internal/services/groups/group_resource_test.go
internal/services/groups/groups_data_source.go
internal/services/groups/groups_data_source_test.go

Also add an acceptance helper to check values with a custom validation func
Closes: #551 
Thanks to @Threpio for initial work in #552

data.azuread_groups: support the mail_enabled and security_enabled properties

---

internal/services/applications/application_data_source_test.go
internal/services/applications/application_resource.go
internal/services/applications/application_resource_test.go
internal/validate/uri.go

azuread_application: support for "myapp://auth" as a public client redirect URI, to support B2C IEF applications

---

internal/services/applications/application_resource.go
internal/services/groups/group_resource.go
internal/services/serviceprincipals/service_principal_resource.go
internal/services/users/user_resource.go

- For applications, service principals, groups and users
- After creating, make a PATCH request with no changes
- Oftentimes if replication is very delayed, the PATCH request will fail
- The SDK handles retries of the PATCH request until it succeeds or times out
Closes: #652

Mitigate some replication delays after creating some resources

---

internal/services/users/user_data_source.go
internal/services/users/user_resource_test.go
internal/services/users/users_data_source.go
internal/utils/odata_query_string.go

This PR addresses https://github.com/hashicorp/terraform-provider-azuread/issues/639.
We need to escape User Principal Names before querying Microsoft Graph.
I'm unable to run acceptance tests at the moment, but I have included a test.

Bugfix: UPN single quote escaping

---

docs/data-sources/application.md

Currently, oauth2_permission_scope is incorrect as the resource within application_data_source.go is oauth2_permission_scopes. Therefore when performing lookups via oauth2_permission_scope, currently this is failing.

Bring documentation inline with resource

---

docs/resources/conditional_access_policy.md

azuread_conditional_access_policy: fix docs to reflect that `All` isn't accepted for role/group conditions

---

GNUmakefile

make tools was erroring on fresh clone:
```
$ make tools
==> installing required tooling...
...
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOPATH || $GOPATH)"/bin v1.32.0
golangci/golangci-lint info checking GitHub for tag 'v1.32.0'
golangci/golangci-lint info found version: 1.32.0 for v1.32.0/darwin/arm64
make: *** [tools] Error 1
```
This PR upgrades the version of golangci-lint to 1.43.0 which seems to install fine.

Upgrade golangci to 1.43.0 - so that `make tools` works on arm64

---

docs/resources/group.md
internal/services/applications/application_resource.go
internal/services/serviceprincipals/service_principal_resource.go

No longer retrieve owner principals when managing applications or service principals. Since we no longer use the `@odata.id` returned by the API, it's not necessary to retrieve owner principals via the `/directoryObjects` endpoint. This can sometimes require additional permissions, which we did not document, and which is undesirable in any case.
Additionally, document additional potentially required permissions for groups as we can't get around this when managing groups, due to necessarily needing to distinguish between different types of owner principals.
Fixes: #703
**Test results**

Don't call /directoryObjects for applications or service principals

---

docs/data-sources/groups.md
internal/services/groups/groups_data_source.go
internal/services/groups/groups_data_source_test.go

Support retrieving groups by a `display_name` prefix, utilizing the API-supported OData filter.

data.azuread_groups: support `display_name_prefix`

---

docs/index.md

I found there were some resources that didn't work as the docs stated when I had my required provider version set to "~> 2.0.0"

Bump provider version in docs

---

internal/services/groups/group_resource.go

Make toggleable features for unified groups Computed and use GetOkExists to avoid sending them when unconfigured
Fixes: #729

Bugfix: avoid setting features for unified groups when unconfigured

---

docs/data-sources/service_principals.md
internal/services/serviceprincipals/service_principals_data_source.go

data.azuread_service_principals: export the `object_id` attribute in the `service_principals` list

---

docs/data-sources/groups.md
docs/data-sources/users.md
internal/helpers/consistency.go
internal/services/groups/group_resource.go
internal/services/groups/group_resource_test.go
internal/services/groups/groups_data_source.go
internal/services/groups/groups_data_source_test.go

Also adds a workaround for an API bug involving group descriptions.
Fixes: #776
Fixes: #782

`data.azuread_groups` - support the `ignore_missing` property

---

internal/clients/builder.go

Bugfix: set the tenant ID correctly when not specified by provider block

---

docs/resources/directory_role_assignment.md
docs/resources/directory_role_member.md
internal/services/directoryroles/client/client.go
internal/services/directoryroles/directory_role_assignment_resource.go
internal/services/directoryroles/directory_role_assignment_resource_test.go
internal/services/directoryroles/directory_role_member_resource.go
internal/services/directoryroles/registration.go

This uses the newer "unified role assignment" endpoints to manage
directory role assignments for built-in roles and custom roles. Also
supports scoping via directory object IDs or apps.
Closes: #742

New resource: `azuread_directory_role_assignment`

---

internal/services/groups/group_data_source.go
internal/services/groups/group_data_source_test.go
internal/services/groups/group_resource_test.go

data.azuread_group: ensure security/mail enabled groups are excluded when explicitly `false` in config

---

internal/helpers/credentials.go

As per the suggestions and comparisons with the power-shell in the issue itself.
Issue link: https://github.com/hashicorp/terraform-provider-azuread/issues/843

Fix for Issue #843 - end_date_relative for application_password

---

docs/guides/service_principal_oidc.md

Add a warning that the OIDC implementation is specific to GitHub actions and cannot be used in a generic way
This warning could then be removed once the work in #869 is done

Add warning that OIDC auth only works in GitHub Actions

---

docs/resources/application.md

Fix: [azuread_application] The 'type' parameter in 'oauth2_permission_scope' block is marked as Required but behaves as Optional #888

---

docs/resources/app_role_assignment.md

I didn't find it intuitive how to assign to the default app role, so I added an example.

Docs/app_role_assignment: add example for role assignment to default app role

---

docs/resources/conditional_access_policy.md
internal/services/conditionalaccess/conditional_access_policy_resource_test.go

Add missing value to "included_applications" attribute for setting no included applications.  If this value isn't set to "None" Terraform fails with the following error:
Error: Could not create conditional access policy
│ 
│   with module.conditional-access.azuread_conditional_access_policy.block_basic_auth_policy,
│   on ../conditional-access/main.tf line 30, in resource "azuread_conditional_access_policy" "block_basic_auth_policy":
│   30: resource "azuread_conditional_access_policy" "block_basic_auth_policy" {
│ 
│ ConditionalAccessPoliciesClient.BaseClient.Post(): unexpected status 500 with OData error: Internal Server Error: There was an internal server error while processing the request. Error ID: c9b4f7ac-cbe5-45fe-8d4c-16961e3b872f

Update conditional_access_policy.md - missing none value for included_applications

---

internal/services/applications/application_resource.go
internal/validate/uri.go
internal/validate/uri_test.go

Using the Graph API, if you try and patch or create an application that has an `IdentifierUris` without a path and a trailing slash, the api will respond with:
```
ApplicationsClient.BaseClient.Patch(): unexpected status 400 with OData error: IdentifierUrisEndsWithSlash: Application alias 'https://mydomain.com/' value is invalid.
```
This PR Extends the function `validate.IsUriFunc` to have a new argument `allowTrailingSlash` and its set to false for `IdentifierUris` validation.

Prevent trailing slash for identifierUris when no path

---

docs/data-sources/directory_roles.md
internal/services/directoryroles/directory_roles_data_source.go
internal/services/directoryroles/directory_roles_data_source_test.go
internal/services/directoryroles/registration.go

This PR adds a data source that enables the lookup of all activated directory roles in the tenant.
My use case for this is as a dynamic way to populate roles in a conditional access policy but I'm sure there are other use cases that would benefit from it.
Down the line we could look to add the ability to filter specific roles based on ID or name much like the `azuread_users` data source
Let me know your feedback and any changes that are needed, thanks!

Add `azuread_directory_roles` data source

---

.gitignore
internal/services/applications/application_resource_test.go
internal/services/applications/applications.go

closes #963
---
Maintainer note: see issue for discussion (manicminer)

fix: oauth2Permissions and appRoles allow dupes

---

docs/resources/service_principal.md

It is possible now to create an application and service principal by making use of a service principal with the `Application.ReadWrite.OwnedBy` permissions. The documentation should be updated to reflect this.

Update service principal permissions requirements

---

docs/resources/service_principal_token_signing_certificate.md
internal/helpers/credentials.go
internal/services/serviceprincipals/parse/credentials.go
internal/services/serviceprincipals/registration.go
internal/services/serviceprincipals/service_principal_token_signing_certificate_resource.go
internal/services/serviceprincipals/service_principal_token_signing_certificate_resource_test.go

This adds a new resource called
`service_principal_token_signing_certificate` that is used to manage the whole lifecycle of token signing certificates used for SAML authentication.
This resource makes use of the `AddTokenSigningCertificate` function that was added to hamilton previously here:
https://github.com/manicminer/hamilton/pull/158
MS Graphs Docs: https://learn.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&tabs=http
As documented in the docs above, when the  `AddTokenSigningCertificate` function is invoked, 3 individual objects are created...
- Verify `keyCredential` (Public Cert)
- Sign `keyCredential` (Private Key)
- `passwordCredential` (Private Key Password)
When the object is returned, it includes the thumbprint, the public key …

Add token signing certificate resource

---

internal/services/groups/group_resource.go
internal/services/groups/group_resource_test.go

Rather than coming up with a heuristic for determining whether a create is likely to be a replacement, we'll omit the duplicate name check at plan time when creating (but keep the check when updating) and defer the check to the create func (i.e. apply time). This is a workaround to be revisited when we move to terraform-plugin-framework at a future point.
Closes: #697
Replaces: #702

azuread_group: fix for issue that prevents replacing a group when `prevent_duplicate_names = true`

---

internal/services/applications/client/client.go

Remove the workaround as the bug is now resolved. This was confirmed to me by Microsoft in a support ticket and I've also no longer been able to reproduce the issue using V1.0 of the API. 
PR change reverses the use of the beta endpoint. 
Original PR to fix bug can be found here https://github.com/hashicorp/terraform-provider-azuread/pull/936

Remove Workaround for US Gov Bug

---

internal/services/users/user_data_source.go

Error message is incorrect for mailNickname logic - trying to use upn vs mailNickname, results in an invalid error message/makes troubleshooting more difficult.
```
│ Error: User not found with email alias: ""
│
│   with module.groupmember["test"].data.azuread_user.user,
│   on ../../../modules/aadgroupassignment/main.tf line 3, in data "azuread_user" "user":
│    3:   mail_nickname = "test@test.com"
│
```

Bug in error message

---

examples/create-for-rbac/main.tf
examples/create-for-rbac/outputs.tf

When I create rbac example using **terraform apply** command found some problems.
1. [Refer to **display_name** of resource **azuread_application** instead of **name**.](https://github.com/hashicorp/terraform-provider-azuread/blob/66c01cca4a3ba0e644ac147420acbe345c6739f1/examples/create-for-rbac/main.tf#L30)
2. [The **private_key_pem** output by resource **tls_private_key** needs to set **sensitive = true**.](https://github.com/hashicorp/terraform-provider-azuread/blob/66c01cca4a3ba0e644ac147420acbe345c6739f1/examples/create-for-rbac/outputs.tf#L14)
` Error: Output refers to sensitive values
│ 
│   on main.tf line 194:
│  194: output "tls_private_key" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root …

Fix error creating rbac example

---

docs/data-sources/application.md
docs/resources/application.md
internal/services/applications/application_data_source.go

azuread_application: document `description` property, also add to data source

---

internal/clients/client.go
internal/provider/provider_test.go
internal/services/applications/application_resource.go
internal/services/groups/group_resource.go
internal/services/serviceprincipals/client_config_data_source.go
internal/services/serviceprincipals/service_principal_resource.go
internal/services/users/client/client.go

Related: https://github.com/hashicorp/terraform-provider-azurerm/pull/20465

Bugfix: retrieve authenticated principal from MS Graph when `oid` claim is missing from access token

---

internal/services/administrativeunits/client/client.go
internal/services/applications/client/client.go
internal/services/groups/client/client.go
internal/services/users/client/client.go

- v1.0 API for applications is broken, see https://github.com/microsoftgraph/msgraph-metadata/issues/273
- Resolves: #1017
- Resolves: #1016
- Beta API for users does not exhibit this issue: https://learn.microsoft.com/en-us/graph/known-issues#showinaddresslist-property-is-out-of-sync-with-microsoft-exchange
- Resolves: #1020
- v1.0 API for groups does not return full membership list, see https://github.com/hashicorp/terraform-provider-azuread/issues/1018
- Resolves: #1018
- SDK uses wrong endpoint for administrative units in v1.0 API, see https://github.com/manicminer/hamilton/issues/222
- Resolves: #1015

Workaround: revert to using the beta API for applications

---

docs/data-sources/directory_roles.md
internal/services/directoryroles/directory_roles_data_source.go
internal/services/directoryroles/directory_roles_data_source_test.go

Just a minor one, it turns out when using this with conditional access policies you need to provide the template IDs not the object IDs.. woops!
Adding them in so they can be easily used

Add `template_ids` to `azuread_directory_roles`

---

internal/services/groups/group_resource.go
internal/services/groups/group_resource_test.go

azuread_group: only send additional fields when absolutely necessary

---

internal/acceptance/check/that.go
internal/acceptance/testcase.go
internal/acceptance/testclient/client.go

Needed since terraform-plugin-sdk v2.24.1 cancels the context for the test provider once the config has been applied, causing checks to fail
Based on the [AzureRM implementation](https://github.com/hashicorp/terraform-provider-azurerm/blob/42367ac6c4799252c9c3ac54da51d2e76314266c/internal/acceptance/check/that.go#L42-L45)

Acceptance testing: build separate client for checks

---

internal/services/groups/group_resource.go
internal/services/groups/group_resource_test.go

Partial workaround for https://github.com/microsoftgraph/msgraph-metadata/issues/92
Closes: #624

Workaround: auto-retry group creation without calling principal as owner

---

docs/resources/application.md

According to the provider docs one of `Directory.ReadWrite.All` or `Application.ReadWrite.All` are sufficient to use the `azuread_application` resource. This is not true. According to my experience and to the official REST api docs just `Application.ReadWrite.All` is required: https://learn.microsoft.com/en-us/graph/api/application-post-applications?view=graph-rest-beta&tabs=http#permissions

Fix api permission docs on azuread_application resource

---

internal/services/serviceprincipals/service_principal_resource.go
internal/services/serviceprincipals/service_principal_resource_test.go

GetOK does not (I believe) return ok when passed an empty set or null value. Therefore the code section is not executed when trying to clear all owners. Resolution matches that for #901 as applied to applications. Reviewed tests and these are the same as those made against applications - though there is a gap in the tests given this issue was not caught but I see no way to address it.

Bugfix: serviceprincipal owner removal #1049

---

docs/resources/group.md
docs/resources/group_member.md

Tested the changes described today and it works. This is a more least-privilege way to grant access to create AAD groups and memberships.

Fix accuracy in documentation of Application permissions for azuread_group and azuread_group_member

---

docs/resources/group.md
internal/services/groups/group_resource.go
internal/services/groups/group_resource_test.go

Writeback configuration should be omitted on creation instead of using the default value, and unsetting `onpremises_group_type` should cause a ForceNew
Fixes: #1067

Fix regression: writeback configuration should be omitted on creation

---

docs/resources/group.md
internal/services/groups/group_data_source.go
internal/services/groups/group_resource.go
internal/services/groups/group_resource_test.go
internal/services/groups/groups.go

- `onpremises_group_type` should be optional+computed to silently ignore an unsettable value, see https://github.com/hashicorp/terraform-provider-azuread/issues/1072 and https://github.com/microsoftgraph/msgraph-metadata/issues/332
- workaround for reading M365-only fields in a non-M365 tenant, see https://github.com/microsoftgraph/msgraph-metadata/issues/333
Resolves: #1072

azuread_group: regression fixes

---

docs/index.md

Fixing typo as per https://developer.hashicorp.com/terraform/plugin/log/managing

Fix typo on debugging docs

---

.github/workflows/acctest-oidc.yaml
.github/workflows/depscheck.yaml
.github/workflows/docs-lint.yaml
.github/workflows/golint.yaml
.github/workflows/link-milestone.yaml
.github/workflows/teamcity-test.yaml
.github/workflows/tflint.yaml
.github/workflows/thirty-two-bit.yaml
.github/workflows/unit-test.yaml
.github/workflows/validate-examples.yaml

Commit is the result of running HashiCorp's internal pinning tool, for all GitHub Actions workflows in the repo.
https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/
Note, this unsolicited PR is a courtesy and has not been tested before submission.  The PR should be evaluated and merged by its responsible team.

Bump all GitHub Actions and pin; avoid deprecated Node 12

---

.goreleaser.yml

Before:
> User-Agent: HashiCorp Terraform/1.6.0-dev (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azuread/dev Hamilton (Go-http-client/1.1) pid-222c6c49-1b0a-5959-a213-6608f9eb8820
After:
> User-Agent: HashiCorp Terraform/1.6.0-dev (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azuread/99.99.99 Hamilton (Go-http-client/1.1) pid-222c6c49-1b0a-5959-a213-6608f9eb8820

provider: ensuring the provider version is appended to the release user agent

---

docs/resources/user.md

The different 2-letter code examples and wording annoyed me whilst reading the documentation.

User Resource - Country Code Examples unified.

---

docs/resources/conditional_access_policy.md
internal/services/conditionalaccess/conditional_access_policy_resource.go
internal/services/conditionalaccess/conditional_access_policy_resource_test.go
internal/services/conditionalaccess/conditionalaccess.go

Adds the `disable_session_resilience` property in the `azuread_conditional_access_policy` resource.
Fixes #931
- Updated docs
- Updated tests

`azuread_conditional_access_policy` - Add `disable_session_resilience` property

---

docs/resources/conditional_access_policy.md
internal/services/conditionalaccess/conditional_access_policy_resource.go
internal/services/conditionalaccess/conditional_access_policy_resource_test.go
internal/services/conditionalaccess/conditionalaccess.go

Fix #985 
I do not know yet how to add tests ; in order to really test this, we need a service principal ID, and by design those IDs are specific to a given Azure Tenant.
Should I add an additional environment variables with a service principal ID to be set to run this test ? What if this is not set, it means the test suite will fail ? Could I even add two variables with two service principal IDs to check that adding multiples items is working ok ?
Thanks in advance

Issue 985 - Add support for clientApplications in conditional access policies

---

internal/services/identitygovernance/access_package_resource_package_association_resource.go

This PR currently uses a modified version of the hamilton package and can be pointed back to the official package if https://github.com/manicminer/hamilton/pull/245 is merged
This will hopefully resolve https://github.com/hashicorp/terraform-provider-azuread/issues/1091

Adding a delete method for `azuread_access_package_resource_package_association`

---

internal/provider/provider.go
internal/provider/provider_test.go

Adds the ability to specify a path to the client ID and client secret in place of supplying their values directly in the provider.
This adds matching capabilities to what was added to the AzureRM provider in https://github.com/hashicorp/terraform-provider-azurerm/pull/21764

Allow for setting client ID / secret through files

---

docs/resources/conditional_access_policy.md
internal/services/conditionalaccess/conditional_access_policy_resource.go

During some recent work I noticed you could not create a CA policy in terraform that only has a terms of use set and no other controls.
This is possible through the portal, the below policy is valid and with this modification applies successfully.
```hcl
resource "azuread_conditional_access_policy" "tou" {
display_name = "Require All Users agree to terms"
state        = "disabled"
conditions {
client_app_types = ["all"]
applications {
included_applications = ["All"]
}
users {
included_users = ["All"]
}
locations {
included_locations = ["All"]
}
}
grant_controls {
operator                      = "OR"
terms_of_use                  = ["<<TOU-GUID>>"]
}
}
```
Creating a policy with neither field is not possible (at least not until authentication strengths are supported) so I have set it to at …

`azuread_conditional_access_policy` set `built_in_controls` to optional

---

docs/resources/access_package_assignment_policy.md

Fixed the issue with the example code for the `azuread_access_package_assignment_policy` resource. The previous example provided in the documentation resulted in a reference to an undeclared resource error when running terraform plan. 
Fixes: #1161

Fix example code of the access_package_assignment_policy resource

---

docs/data-sources/group.md
internal/services/groups/group_data_source.go
internal/services/groups/group_data_source_test.go

Adding the option to look up `data.azuread_group` items by `mail_nickname` field.
The need for this arose as we ran into the issue with display name not necessarily being unique in a larger AAD instance, thus making it impossible to pick the data for such a group from AAD without resorting to the object id. This isn't really possible in our case, as obtaining the object UUID from the group name is the reason we're using this data source in the first place 🙈 .
I've also added tests based on the ones already present for the `displayName` option but was not able to run the acceptance tests due to missing a proper Azure subscription satisfying the requirements to run those.

data.azuread_group: allow lookup by mail_nickname

---

docs/index.md

Adds missing documentation for https://github.com/hashicorp/terraform-provider-azuread/pull/1189

Add documentation for new provider properties

---

docs/resources/directory_role_eligibility_schedule_request.md
internal/services/directoryroles/client/client.go
internal/services/directoryroles/directory_role_eligibility_schedule_request_resource.go
internal/services/directoryroles/directory_role_eligibility_schedule_request_resource_test.go
internal/services/directoryroles/registration.go

This PR adds a `azuread_directory_role_eligibility_schedule_request` resource. We would like to be able to manage eligible roles in PIM with terraform. This PR lets us do it like this:
```
resource "azuread_directory_role_eligibility_schedule_request" "example" {
role_definition_id = "00000000-0000-0000-0000-000000000000"
principal_id       = "00000000-0000-0000-0000-000000000000"
directory_scope_id = "/"
justification      = "abc"
}
```
This is a pretty bare-bones version of the resource, but it gives us what we need for now. I have also opened a PR in https://github.com/manicminer/hamilton here: https://github.com/manicminer/hamilton/pull/204.
Related to https://github.com/hashicorp/terraform-provider-azuread/issues/68.
As I wrote in the other PR, I havn't written any tests, as I wanted …

Add azuread_directory_role_eligibility_schedule_request resource

---

internal/services/groups/group_member_resource.go

This PR proposes a fix for issue #1172 regarding `azuread_group_member` resource failing to refresh  when the referenced group is missing.
It handles the case where `client.ListMembers()` returns a 404 error (missing group) by removing the group member from the state.
I could validate with [this simple bug reproducer](https://github.com/LoicBer/azuread-groupmember-bug) that this change solves the issue.
Here the output I get when running `terraform plan` when the group ID referenced by the group member has changed:
https://gist.github.com/LoicBer/53a8b974067d0ca0cfacb50f9a9ee911
Terraform wants to remove the member from the state and recreate the member with the new group ID, which is the expected behavior.

Fix group member resource to survive refresh when group is missing

---

internal/services/applications/application_certificate_resource.go
internal/services/applications/application_federated_identity_credential_resource.go
internal/services/applications/application_password_resource.go
internal/services/applications/application_pre_authorized_resource.go

This works around some existing configurations where a diff may arise as a result of the recent state migration to update the resource ID for `azuread_application` to use a typed ID.
Where an existing configuration mistakenly references the `id` attribute for an `azuread_application` resource, expecting it to contain a bare object ID, this avoids a subsequent diff where the existing bare UUID and the prospective ID point to the same application.
Fixes: #1218

Applications: DiffSuppressFunc for `application_object_id`

---

docs/data-sources/application_published_app_ids.md
docs/resources/service_principal.md

This pull request fixes the references to `application_id` remaining in `azuread_service_principal` and `azuread_application_published_app_ids` since `application_id` has been deprecated.

Fix `application_id` references in `azuread_service_principal` & `azuread_application_published_app_ids`

---

docs/resources/conditional_access_policy.md
internal/services/conditionalaccess/conditional_access_policy_resource.go
internal/services/conditionalaccess/conditional_access_policy_resource_test.go
internal/services/conditionalaccess/conditionalaccess.go

Implement conditional access policies guests_or_internal_users

---

docs/resources/application_api_access.md

[Example](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application_api_access#example-usage) refers to created resource, but should use the declared data resource instead.

Fix example for azuread_application_api_access

---

docs/resources/application.md
docs/resources/application_registration.md

ref: https://github.com/hashicorp/terraform-provider-azuread/issues/1227#issuecomment-1810376519

docs: document the `id` attribute for `azuread_application`

---

docs/data-sources/application.md
internal/services/applications/application_data_source.go

ref: https://github.com/hashicorp/terraform-provider-azuread/issues/1227#issuecomment-1814873000

`data.azuread_application`: updated resource ID

---

docs/resources/named_location.md
internal/services/conditionalaccess/named_location_resource.go
internal/tf/validation/net.go
internal/tf/validation/net_test.go

From the [docs](https://learn.microsoft.com/en-us/entra/identity/conditional-access/location-condition#ip-address-ranges):
closes #855

azuread_named_location: validation for `ip_ranges` property

---

internal/services/conditionalaccess/named_location_data_source.go

bugfix: correctly handle no results for `data.azuread_named_location`

---

docs/resources/service_principal_password.md

The example is incorrect - azuread_service_principal only allows you to specify client_id not application_id

Update azuread_service_principal_password documentation to correct azuread_service_principal example

---

docs/data-sources/service_principals.md
internal/services/applications/application_data_source.go

I was recently using this provider and had some confusion from my side as I was unaware client id and application id were synonomous for one another, I use the terraform provider docs religiously and I believe that because application id is a property that is now deperecated this description should be changed to match what the provider expects, which from what I can tell is client id

docs: add to resource_app_id description and fix typos in service_principals.md

---

internal/services/applications/application_identifier_uri_resource.go
internal/services/applications/application_resource.go

Fix #1342
Related #951
I have tried to call API using various patterns.
Test case|`IsAppUri()`|Actual API|Trail
---|---|---|---
(empty string)|Invalid|Invalid|<img width="1029" alt="trail" src="https://github.com/hashicorp/terraform-provider-azuread/assets/1155067/d458b35e-e475-485d-90cd-1df8498db2a1">
`www.example.com?query=param`|Invalid|Invalid|<img width="1023" alt="trail" src="https://github.com/hashicorp/terraform-provider-azuread/assets/1155067/746dbf8e-6251-4243-89ae-be6757d3c6f1">
`this is invalid a url for app with patch!`|Invalid|Invalid|<img width="1033" alt="trail" src="https://github.com/hashicorp/terraform-provider-azuread/assets/1155067/7d0e7223-b50f-46cc-8c51-8909c04c3d0c">
`arn:aws:iam::123456789012:user/johndoe`|Invalid|**Valid**|<img width="1024" alt="trail" …

Relaxed validation for identifier_uri attribute in azuread_application_identifier_uri resource

---

docs/guides/service_principal_oidc.md

- In the `service_principal_oidc.md` document, it explains using ENV VARs for configuring the client, sub, and tenant ID env vars; as well as the use of the `OIDC` env var flavours available.
- Since the `USE_OIDC` option is also exposed as a env var, include this in the example. It makes sense to also use this when performing environment based configuration for OIDC access.

Include Example Of ARM_USE_OIDC

---

docs/resources/group.md

Found through trial and error that both `RoleManagement.ReadWrite.Directory` and `Directory.ReadWrite.All` are required for `assignable_to_role` property.

Doco update for Groups

---

docs/guides/azure_cli.md

This is a documentation only update to provide details on how to use az cli --service-principal and az cli --identity login since support was added in 2.35.0.

docs: update docs to show service principal login is now supported

---

docs/resources/application.md

Since version 2.0.0 the `group_membership_claims` are expected to be a set of strings (see https://github.com/hashicorp/terraform-provider-azuread/blob/79f6519777b7676825d2713c26d77e6a6d25d494/CHANGELOG.md?plain=1#L767).
If a string instead of a set of strings is provided, the following error occurs:
```
│ Error: Incorrect attribute value type
│ 
│   on ../../modules/core-infra/aad-app.tf line 79, in resource "azuread_application" "aad-app":
│   79:   group_membership_claims = "SecurityGroup"
│ 
│ Inappropriate value for attribute "group_membership_claims": set of string
│ required.
```
Not sure if any combination of possible values works. Your feedback would be appreciated.

Adjust documentation for group_membership_claims accepted values

---

internal/services/applications/application_pre_authorized_resource.go
internal/services/applications/application_pre_authorized_resource_test.go

Fix to issue: 1296 azuread_application_pre_authorized does not properly destroy

---

docs/resources/group.md
internal/services/groups/group_resource.go

azuread_group: support `SkipExchangeInstantOn` for `behaviors`

---

docs/resources/synchronization_job_provision_on_demand.md
internal/services/synchronization/registration.go
internal/services/synchronization/synchronization.go
internal/services/synchronization/synchronization_job_provision_on_demand_resource.go
internal/services/synchronization/synchronization_job_provision_on_demand_resource_test.go

Hey @manicminer,
I have tested this with an AWS SSO configured app and it worked well, however I don't have access to an Azure tenant I can test the providers functional tests on. Not sure how best to proceed atm.
```
Terraform will perform the following actions:
+ resource "azuread_synchronization_job_provision_on_demand" "example" {
+ id                   = (known after apply)
+ job_id               = "aWSSingleSignon.hidden"
+ service_principal_id = "hidden"
+ parameters {
+ rule_id = "hidden"
+ subjects {
+ object_id        = "hidden"
+ object_type_name = "Group"
}
}
}
Plan: 1 to add, 0 to change, 0 to destroy.
Do you want to perform these actions?
Terraform will perform the actions described above.
Only 'yes' will be accepted to approve.
Enter a value: yes …
```

fixed #1031 adds provision on demand

---

internal/services/identitygovernance/privileged_access_group_assignment_schedule_resource.go
internal/services/identitygovernance/privileged_access_group_eligiblity_schedule_resource.go
internal/services/identitygovernance/privileged_access_group_schedule.go
internal/services/policies/group_role_management_policy_data_source.go
internal/services/policies/group_role_management_policy_resource.go

bugfix: resolve several potential crashes in new PIM resources

---

docs/data-sources/application.md
internal/services/applications/application_data_source.go
internal/services/applications/application_data_source_test.go

This PR introduces a small feature to the `azuread_application` data source that allows us to get the application based on an identifying URI. This is a feature we would really like to use. It looks like this:
```terraform
data "azuread_application" "example" {
identifier_uris  = [
"api://example-app",
]
}
```
I've implemented it in a way where you can provide a list of one element to the `identifier_uris` field, instead of introducing another field called `identifier_uri` that is just a string, as I thought it might be easy to mix up the two fields, but would love some input on this. I added an error if more than one element is provided in `identifier_uris`.

feat: allow data.azuread_application lookup using identifier_uri

---

internal/services/serviceprincipals/service_principal_data_source.go
internal/services/serviceprincipals/service_principal_data_source_test.go

data.azuread_service_principal: display name comparison should be case-insensitive

---

internal/services/users/user_resource.go

bugfix: run d.Partial() to avoid setting invalid password to state when a user update fails

---

.github/workflows/gencheck.yaml
.github/workflows/provider-test.yaml
.github/workflows/unit-test.yaml

👋 Greetings! 
To align with Github’s removal of [custom labels on larger runners](https://github.blog/changelog/2023-02-15-github-actions-removal-of-additional-label-option-for-github-hosted-larger-runners/), this PR is updating the labels defined in your Github Action jobs. Moving forward, only one label (the name of GH runner type)  will be needed to ensure an appropriate runner is used for your GHA job.
Please review for accuracy and merge before May 27, 2024. Thank you!

use single runner label for custom-linux-large

---

GNUmakefile
README.md
main.go

Adds support for runtime debugging of the provider - https://developer.hashicorp.com/terraform/plugin/sdkv2/debugging

feat: add runtime provider debugging capability

---

docs/data-sources/users.md
internal/services/users/user_resource_test.go
internal/services/users/users_data_source.go
internal/services/users/users_data_source_test.go

Test results:
<br>
<br>
Closes: #1297

data.azuread_users: support for the `mails` property

---

internal/services/applications/application_resource.go
internal/services/applications/application_resource_test.go

Support `ignore_changes` lifecycle argument for `app_role`, `oauth2_permission_scope`, `identifier_uris`, `optional_claims`, and `required_resource_access`
Fixes: #1344

azuread_application: support `ignore_changes` lifecycle argument

---

go.mod
go.sum
internal/services/applications/application_redirect_uris_resource.go
internal/services/applications/application_registration_resource.go
internal/services/applications/application_resource.go
internal/services/applications/client/client.go
vendor/github.com/manicminer/hamilton/msgraph/application_templates.go
vendor/modules.txt

> [!IMPORTANT]
> Depends on https://github.com/manicminer/hamilton/pull/285, requires rebase prior to merging
The `/instantiate` operation can return a 404 whlst also processing the request completely normally. This leads to orphaned objects in the directory, and a resource that cannot successfully Create.
Work around this by polling for the application and service principal that you'd expect to see created out-of-band, whenever a 404 is received. Also set a temporary `displayName` for the application, as this is the only means we have to identify the resulting object is the one we are looking for.
Unfortunately this means that this workaround cannot be implemented for the `azuread_application_from_template` resource, since that resource intentionally avoids changing the implicitly …

`azuread_application`: work around very buggy API when instantiating from template

---

internal/services/applications/application_resource.go
internal/services/applications/application_resource_test.go

Avoids marking all attributes as sensitive if the entire resource is used for an output variable
Fixes: #1421

regression: `azuread_application` - don't populate the `password` block unless specified in config

---

internal/services/conditionalaccess/conditional_access_policy_resource_test.go
internal/services/conditionalaccess/conditionalaccess.go

This fixes some incorrect logic around enabling session controls when only `sign_in_frequency_interval = "everyTime"` is specified.
Unfortunately this is currently blocked due to a possible API bug - this field doesn't seem to be accepted by the v1.0 API [contrary to documentation](https://learn.microsoft.com/en-us/graph/api/resources/signinfrequencysessioncontrol?view=graph-rest-1.0). Changing the API version in the request to `beta` allows the request to complete.
<br><br>
Closes: #1416

bugfix: ensure `sessionControls.isEnabled: true` when specifying `sign_in_frequency_interval = "everyTime"`

---

docs/resources/application_identifier_uri.md
docs/resources/application_owner.md
docs/resources/application_redirect_uris.md
docs/resources/application_registration.md
internal/services/applications/application_data_source_test.go
internal/services/applications/application_federated_identity_credential_resource_test.go
internal/services/applications/application_redirect_uris_resource_test.go
internal/services/applications/application_registration_resource_test.go
internal/services/applications/application_resource_test.go
internal/services/serviceprincipals/service_principal_resource_test.go

Parts of our documentation and code reference a (previously) unregistered domain - `hashitown.[com|net]`. To prevent confusion, domain squatting, etc, this change replaces all references with the iana official example domain: `example.com`
First commit only changes docs. Second commit changes references in code (only tests)
Commands were roughly:
`ag -l hashitown | xargs sed -i "" 's/hashitown.com/example.com/g'`
`ag -l hashitown | xargs sed -i "" 's/hashitown/hashitown.example.com/g'`

Removing references to "hashitown" domain

---

docs/data-sources/directory_object.md

Fix formatting of attribute references in docs

docs: Fix formatting of directory_object

---

internal/services/applications/application_password_resource_test.go
internal/services/applications/application_resource.go
internal/services/applications/application_resource_test.go

FIX:
Update function of application resource to update / remove the password when the inline `password` block is removed.

bugfix: azuread_application - delete password block

---

docs/guides/managed_service_identity.md

The `identity` in `azurerm_linux_virtual_machine` resource should be a nested block, so the `=` is incorrect.

docs: correct `identity` snippet in doc

---

docs/resources/app_role_assignment.md

This small PR updates the import statement for the azuread_app_role_assignment.
I noted a change when recently using it.
```
Error: parsing "d00*****-****-****-****-*****39b503c/appRoleAssignment/Jno_******************************NWf5jBrA4": parsing the ServicePrincipalIdAppRoleAssignedTo ID: the number of segments didn't match
│ 
│ Expected a ServicePrincipalIdAppRoleAssignedTo ID that matched (containing 4 segments):
│ 
│ > /servicePrincipals/servicePrincipalId/appRoleAssignedTo/appRoleAssignmentId
│ 
│ However this value was provided (which was parsed into 0 segments):
│ 
│ > d00*****-****-****-****-*****39b503c/appRoleAssignment/Jno_******************************NWf5jBrA4
│ 
│ The following Segments are expected:
│ 
│ * Segment 0 - this should be the literal value "servicePrincipals" …
```

docs: update import statement for app_role_assignment

---

docs/data-sources/user.md
docs/resources/user.md
internal/services/users/user_data_source.go
internal/services/users/user_data_source_test.go
internal/services/users/user_resource.go
internal/services/users/user_resource_test.go

azuread_user: support employee hire date

---

docs/resources/administrative_unit.md
docs/resources/administrative_unit_member.md
docs/resources/administrative_unit_role_member.md
docs/resources/authentication_strength_policy.md
docs/resources/conditional_access_policy.md
docs/resources/named_location.md

My goal with this pull request is to improve the documentation for the terraform import commands for some resource types:
- administrative units
- administrative unit members
- administrative unit role member
- authentication strength policies
- conditional access policies
- named locations
As this is my first fork pull request, I hope this way is correct to do it. If not, please let me know so I can improve the pull request.

Fixing some import commands in docs

---

docs/resources/group.md

azuread_group: document all application permissions needed when creating groups inside administrative units

---

docs/resources/named_location.md
internal/services/conditionalaccess/conditionalaccess.go
internal/services/conditionalaccess/named_location_data_source.go
internal/services/conditionalaccess/named_location_data_source_test.go
internal/services/conditionalaccess/named_location_resource.go
internal/services/conditionalaccess/named_location_resource_test.go

In `azuread_named_location` add support for the `country_lookup_method` parameter. This specifies method of detecting country the user is located in. Possible values are `clientIpAddress` for IP-based location and `authenticatorAppGps` for Authenticator app GPS-based location.  Defaults to `clientIpAddress`.
Graph API documentation: https://learn.microsoft.com/en-us/graph/api/resources/countrynamedlocation?view=graph-rest-1.0 
Fix #1427

azuread_named_location: Implement support for the country_lookup_method parameter

---

internal/services/groups/group_resource.go

azuread_group: fix bug preventing creation retry when caller owner causes duplicate value error

---

internal/services/identitygovernance/parse/access_package_resource_catalog_association_id.go

azuread_access_package_resource_catalog_association: allow originId containing `/`, e.g. URIs

---

docs/resources/conditional_access_policy.md
internal/services/conditionalaccess/conditional_access_policy_resource_test.go

Improve documentation to make the authentication strength policy better defined. Add a test case to authentication strength policy with hard-coded values, such as the _Phishing resistant MFA_ policy. This patch does not change the ID handling introduced in #1499 and keeps backwards compatibility, but the add test will fail if the behavior changes again.
Fix #1547

azuread_conditional_access_policy: Authentication strength policies hard-coded values path

---

internal/services/policies/group_role_management_policy_resource.go
internal/services/policies/group_role_management_policy_resource_test.go

This PR makes the `approval_status` consistent with the other properties in this resource that are Computed Optional, and resolves a bug where, when an `activation_rules` block is configured, previously an impossible change would always appear in plans.
I added a test (`TestGroupRoleManagementPolicy_activationRules`) that fails when run against the `main` branch:
```
testcase.go:122: Step 1/2 error: After applying this test step, the non-refresh plan was not empty.
stdout:
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "azuread_group_role_management_policy" "test" {
id           = …
```

`azuread_group_role_management_policy` - stop drift by making `approval_status` computed

---

docs/guides/service_principal_oidc.md
docs/index.md
go.mod
go.sum
internal/provider/provider.go
internal/provider/provider_test.go
vendor/github.com/hashicorp/go-azure-sdk/sdk/auth/README.md
vendor/github.com/hashicorp/go-azure-sdk/sdk/auth/ado_pipeline_oidc_authorizer.go
vendor/github.com/hashicorp/go-azure-sdk/sdk/auth/auth.go
vendor/github.com/hashicorp/go-azure-sdk/sdk/auth/config.go
vendor/github.com/hashicorp/go-azure-sdk/sdk/client/client.go
vendor/modules.txt

Update the go-azure-sdk to v0.20250131.1134653, with a couple of fixes below:
- Provider config: The GtihubOIDCRequest(URL|Token) fields in the sdk has been renamed to removing the Github prefix.
Meanwhile, this PR, as its azurerm [counterpart](https://github.com/hashicorp/terraform-provider-azurerm/pull/28674), exposes the ADO OIDC changes to the users:
1. Add a new provider property: `ado_pipeline_service_connection_id`
2. Extends the env var for the provider property `oidc_request_token`, to include `SYSTEM_ACCESSTOKEN`
3. Extends the env var for the provider property `oidc_request_url`, to include `SYSTEM_OIDCREQUESTURI`
```yaml
name: terraform-provider-azuread OIDC test
on: [workflow_dispatch]
permissions:
id-token: write
contents: read
jobs:
build-and-deploy:
runs-on: ubuntu-latest …
```

dependencies: update go-azure-sdk to v0.20250131.1134653

---

.github/labeler-issue-triage.yaml
internal/services/groups/group_without_members_resource.go
internal/services/groups/group_without_members_resource_test.go
internal/services/groups/registration.go

This PR introduces a Group resource that omits management and exposure of group members. This resource is intended for use cases where a Group needs to be managed via terraform, but the members of the group are not of concern, typically where the members list is sufficiently large that performance problems are encountered, and/or members are managed by other means.
closes #954 - Since there is no current way to improve the linear performance problem with the List() call, the `azuread_group` resource cannot be changed to satisfy a performance improvement.

New Resource: `azuread_group_without_members`

---

internal/services/directoryroles/directory_role_resource.go

This PR fixes the problem described in #1526.
It seems like the Graph Endpoint `GET /directoryRoles` changed when working with filters. 
When querying for roles which have not been initialized in a tenant it now returns `200 OK` with an empty value instead of previously returning `404 NOT FOUND`
This PR changes to logic of the `azuread_directory_role` resource to also activate the role when an empty set of roles is returned to the filter query.
closes #1526

azuread_directory_role: fix for changes in Graph API

---

internal/services/applications/application_pre_authorized_resource.go

Range breaks at first pre_authed app with a different id during deletion, but we must preserve all existing pre_authorized apps with a different id.
Shall fix [#1584](https://github.com/hashicorp/terraform-provider-azuread/issues/1584)

`azuread_application_pre_authorized` - Fix unexpected removal of unmanaged pre-authorized apps

---

docs/index.md

The version in the example is outdated.

doc(index.md): bump version in example
